### ISSUE TITLE
Sending empty Array is returning "Invalid JSON content in request.". Which should not be the case

### ISSUE THREAD

**Issue by drrasic** [trax-project/trax2-framework#1]
**Problem:**
Sending request with empty Array is returning "400: Invalid JSON content in request.". Which should not be the case because empty array is Valid JSON.

**Why:**
Problem code on line 42 in /xapi-store/src/Traits/AcceptJsonRequests.php
Because Empty Array in PHP is falsey, writting IF condition like this will go to exception when given empty array.
```
$content = HttpRequest::content($request);
if (!$json = json_decode($content)) {
  throw new XapiBadRequestException('Invalid JSON content in request.');
}

return $json;
```

**Simple fix:**
adding another condition inside.

```
$content = HttpRequest::content($request);
if (!$json = json_decode($content)) {
  if (!is_array($json)) {
    throw new XapiBadRequestException('Invalid JSON content in request.');
  }
}

return $json;
```

**What got me here:**
Using Moodle Logstore plugin to send xapi statements to Trax LRS.
Statemens are sent in bulk by cronjob and if there are no statements in set period, plugin will send '[]' - empty array, which causes some infinite loops in their code if they recieve 400 exception for that (should be fixed). Other tested LRS-s return 200 in this case.

**Comment by sfraysse** [comment]
Hi @drrasic,
Thank you for this feedback. I made the change on the beta4 branch.
To update your TRAX LRS installation: https://github.com/trax-project/trax2-starter-lrs#updates
